In [1]:
import numpy as np # operações matriciais
from scipy import linalg as la # alguns métodos de algebra linear para comparação

In [2]:
def solve_upper(U,b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n-1,-1,-1): # começa da última linha em direção à primeira
        s = np.dot(U[i,i+1:],x[i+1:]) # calcula a soma dos elementos da linha atual
        x[i] = (b[i]-s)/U[i,i] # calcula o valor de x para a linha atual
    return x

In [3]:
def solve_lower(L,b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n): # começa da primeira linha em direção à última
        s = np.dot(L[i,:i],x[:i]) # calcula a soma dos elementos da linha atual
        x[i] = (b[i]-s)/L[i,i] # calcula o valor de x para a linha atual
    return x

In [4]:
def LU(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n, n))
    
    for i in range(n):
        # Calcula os elementos da linha i da matriz U
        for j in range(i, n):
            U[i, j] = A[i, j] - np.dot(L[i, :], U[:, j])
        
        # Calcula os elementos da coluna i da matriz L
        for j in range(i+1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :], U[:, i])) / U[i, i]
        
    
    # Retorna as matrizes L e U
    return L, U


In [5]:
def solve_LU(A,b):
    L,U = LU(A)
    # Ax = LU x = b
    # Ux = y
    y = solve_lower(L,b) # Ly = b
    x = solve_upper(U,y) # Ux = y
    return x

In [6]:
# Exemplo de utilização para solução de sistema linear

A = np.array(
    [
    [5,2,1],
    [3,1,4],
    [1,1,3]
    ]
)
b = np.zeros((3,1))
b[0] = 0
b[1] = -7
b[2] = -5


x = solve_LU(A,b)
print(x)
print(A@x)

[-4.4408921e-16  1.0000000e+00 -2.0000000e+00]
[ 0. -7. -5.]


In [7]:
# Verificar número de condição:
c = np.linalg.cond(A)
print("Número de condição de A",c)

# Exemplo de matriz mal condicionada
M = la.hilbert(5)
print()
print('Matriz mal consicionada:')
print('M =\n',M)
print('Número de condição de M: ',np.linalg.cond(M))

Número de condição de A 13.912163804268793

Matriz mal consicionada:
M =
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
Número de condição de M:  476607.2502422687
