In [2]:
import numpy as np

## Polinômios em numpy

- Os polinômios são definidos atraves de um vetor de coeficientes.
- O tamanho do vetor determina o grau do polinomio
    - Um vetor de tamanho n+1 representa um polinômio de grau n
    - Exemplo: [3,-2,7] tem tamanho 3, logo representa um polin^mio de grau 2
- Cada elemento representa o coeficiente do polinômio, indo de maior para menor grau
    - Exemplo: [3,-2,7] representa $x^2 - 2x + 7$

In [3]:
c = [3,-2,7]

# Calcular o valor do polinômio em um ponto:
y = np.polyval(c,2) # P(2)
print(y)

# Calcular o valor do polinômio em vários pontos:
x = [1,2,3,4]
y = np.polyval(c,x) # P(2)
print(y)

15
[ 8 15 28 47]


In [4]:
# Criando a matriz de vandermond

x = np.array([-1,0,3])
y = np.array([15,8,-1])

n = x.shape[0]
A = np.ones((n,n)) #inicializa matriz

for i in range(1,n):
    A[:,i] = x**i # maneira ineficiente: calcula potências
    A[:,i] = A[:,i-1]*x # maneira eficiente: reutiliza os cálculos da iteração anterior


In [5]:
# Calculando os coeficientes do polinômio interpolador:

# Sistema Ac = y
c = np.linalg.solve(A,y)

# neste caso, o vetor está invertido, ou seja, os coeficientes estão do menor pro maior grau

#inverte o vetor:

c = np.flip(c)

print('coeficientes:\t',c)
print('interpol.:\t',np.polyval(c,x))
print('y:\t\t',y)

coeficientes:	 [ 1. -6.  8.]
interpol.:	 [15.  8. -1.]
y:		 [15  8 -1]


In [6]:
#Multiplicação de polinomios:
p1 = [1, -2] # x -2
p2 = [3, 5] # 3x +5

p3 = np.polymul(p1,p2) # p1 * p2 = (x-2)(3x+5) = 3x**2 -x -10
print(p3)

[  3  -1 -10]


In [7]:
#Polinômios de lagrange:

L0 = [1.] # Polinômio neutro/ unitário
d0 = 1. # ponto para trabalhar com ponto flutuante e não inteiros
for k in range(n):
    if k == 0:
        continue
    L0 = np.polymul(L0, [1, -x[k]])
    d0 *= x[0] - x[k]
L0 /= d0

L1 = [1.] # Polinômio neutro/ unitário
d1 = 1.
for k in range(n):
    if k == 1:
        continue
    L1 = np.polymul(L1, [1, -x[k]])
    d1 *= x[1] - x[k]
L1 /= d1

L2 = [1.] # Polinômio neutro/ unitário
d2 = 1.
for k in range(n):
    if k == 2:
        continue
    L2 = np.polymul(L2, [1, -x[k]])
    d2 *= x[2] - x[k]
L2 /= d2

pol_lag = y[0]*L0 + y[1]*L1 +  y[2]*L2

print(pol_lag)

[ 1. -6.  8.]
