In [24]:
import numpy as np
from numpy import linalg as la

In [25]:
A = np.random.rand(5,5)
A

array([[0.42586196, 0.55206191, 0.01299301, 0.30975235, 0.75254807],
       [0.75099292, 0.43363015, 0.32775393, 0.56406647, 0.24423937],
       [0.30459351, 0.47395473, 0.86433559, 0.6077705 , 0.3154188 ],
       [0.76705991, 0.7757902 , 0.55970279, 0.23522036, 0.95428724],
       [0.1153204 , 0.1714628 , 0.7721471 , 0.02231069, 0.03868811]])

In [26]:
D = np.diag(np.diag(A))
L = np.tril(A,-1)
R = np.triu(A,1)
print(L+D+R)

[[0.42586196 0.55206191 0.01299301 0.30975235 0.75254807]
 [0.75099292 0.43363015 0.32775393 0.56406647 0.24423937]
 [0.30459351 0.47395473 0.86433559 0.6077705  0.3154188 ]
 [0.76705991 0.7757902  0.55970279 0.23522036 0.95428724]
 [0.1153204  0.1714628  0.7721471  0.02231069 0.03868811]]


In [27]:
def jacobi(A,b,x0 = None, maxIt = 50, tol=1e-4):
    if x0 is None:
        x0 = np.ones_like(b)
    D = np.diag(np.diag(A))
    L = np.tril(A,-1)
    R = np.triu(A,1)
    n = A.shape[0]
    # for i in range(n):
    #     D[i,i] = 1/D[i,i]

    invD = la.inv(D)
    B = -invD @ (L+R) # -D^-1(L+R)
    g = invD @ b # D^-1 b

    for it in range(maxIt):
        x = B@x0 + g

        err = np.linalg.norm(x - x0)/ np.linalg.norm(x)
        if err < tol:
            return x, it
        
        x0 = x

    print('Maximo de iteração atingido')
    return x,maxIt
    

In [28]:
def gauss_seidel(A, b, x0=None, maxIt=50, tol=1e-4):
    if x0 is None:
        x0 = np.ones_like(b)
    L = np.tril(A, -1)
    U = np.triu(A, 1)
    D = np.diag(np.diag(A))
    n = A.shape[0]
    invD_L = la.inv(D + L)
    B = -invD_L @ U
    g = invD_L @ b

    for it in range(maxIt):
        x = B @ x0 + g

        err = la.norm(x - x0) / la.norm(x)
        if err < tol:
            return x, it

        x0 = x

    print('Máximo de iterações atingido.')
    return x, maxIt

In [30]:
A = np.array([
[5, 1, 1], [3, 4, 1], [3, 3, 6]
]
)

b = np.zeros((3,1), dtype=float)
b[0] = 5
b[1] = 6
b[2] = 0

x,it = gauss_seidel(A,b, tol=1e-8)
print(f'Solução encontrada {x}, em {it} iterações')

Solução encontrada [[ 1.]
 [ 1.]
 [-1.]], em 11 iterações
